### ISSUE TITLE
Adapting to non-poker games?

### ISSUE THREAD

**Issue by cpennington** [TinkeringCode/Deep-CFR#3]
This was the first result as I looked for a DeepCFR implementation, and I was wondering how feasible you think it would be to adapt it to a different hidden information game? Would supplying a new `game_cls` with alternate implementations just work? Or is the more poker knowledge/assumptions embedded in the code?

**Comment by EricSteinberger** [comment]
That would require quite heavy changes, I fear. PokerRL, the underlying framework, was built specifically for poker.
